plugins {
    id 'application'
}

group = 'dev.trly.java.example.primitive.wrappers'
version = '1.0.0'

repositories {
    mavenCentral()
}

application {
    mainClass = 'dev.trly.java.example.primitive.wrappers.SensorWindowApp'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.addAll(['-Xlint:deprecation', '-Xlint:removal'])
}
