plugins {
    id 'application'
    id "org.sonarqube" version "7.3.1.8318"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

sonar {
  properties {
    property "sonar.projectKey", "deprecated-java-api-demo-5"
    property "sonar.projectName", "deprecated-java-api-demo-5"
  }
}

group = 'dev.trly.java.example.primitive.wrappers'
version = '1.0.0'

repositories {
    mavenCentral()
}

application {
    mainClass = 'dev.trly.java.example.primitive.wrappers.SensorWindowApp'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.addAll(['-Xlint:deprecation', '-Xlint:removal'])
}
