plugins {
    id 'application'
}

group = 'dev.trly.java.example.primitive.wrappers'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.slf4j:slf4j-api:2.0.16'
    runtimeOnly 'org.slf4j:slf4j-simple:2.0.16'
}

application {
    mainClass = 'dev.trly.java.example.primitive.wrappers.SensorWindowApp'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.addAll(['-Xlint:deprecation', '-Xlint:removal'])
}
